dwm_autostart: bugfixes and minor improvements

diff --git a/.scripts/dwm/dwm_autostart b/.scripts/dwm/dwm_autostart
--- a/.scripts/dwm/dwm_autostart
+++ b/.scripts/dwm/dwm_autostart
@@ -5,6 +5,9 @@
 #   | |   | |_/\| |-|||  __/| \_/||    /  | |
 #   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/
 
+# start by setting the wallpaper. It's the first thing people notice.
+wallpaper current
+
 # start by killing all 'dwm_autostart' processes except this one:
 ps aux | grep -ie dwm_autostart | grep -v grep | awk '{print $2}' | sed "/$$/d" | xargs kill -9 &
 
@@ -22,9 +25,6 @@ start(){
 # enable hotkeys
 start sxhkd
 
-# set wallpaper
-start wallpaper current
-
 # notifications
 start dunst
 
@@ -40,11 +40,17 @@ start xautolock -time 10 -locker validate_and_lock_screen
 # make the mouse invisible after a brief period of not using it.
 start unclutter
 
+# enable x settings daemon
+start xsettingsd
+
 # update xrdb database
 start xrdb "$HOME/.Xresources"
 
-# enable x settings daemon
-start xsettingsd
+# export possible screenlayouts and set default one with `arandr`
+default_screenlayout >> "$HOME"/.local/share/dwm_autostart.log 2>> "$HOME"/.local/share/dwm_autostart.errors.log
+
+# enable transparent windows (doing this with 'start' doesn't work)
+picom --daemon --experimental-backends >> "$HOME"/.local/share/dwm_autostart.log 2>> "$HOME"/.local/share/dwm_autostart.errors.log
 
 # conky dashboards (same one on three monitors)
 if ! pidof conky >/dev/null 2> /dev/null; then
@@ -52,6 +58,9 @@ if ! pidof conky >/dev/null 2> /dev/null; then
     conky -x -1860 >/dev/null 2>&1 &
     conky -x -3780 >/dev/null 2>&1 &
 fi
+
+# starting the previous daemons might have messed with the wallpaper... set it again.
+wallpaper current
 
 # set cursor speed
 # wrapped into loop, as sometimes this inexplicably stops working
@@ -77,7 +86,7 @@ done &
 # check battery status every 10 minutes
 while true; do
     sleep 10s
-    cat /sys/class/power_supply/BAT* > /dev/null 2> /dev/null || break
+    cat /sys/class/power_supply/BAT*/capacity > /dev/null 2> /dev/null || break
     capacity="$(cat /sys/class/power_supply/BAT*/capacity | head -1)"
     [ -z "$capacity" ] && break
     batstatus=$(cat /sys/class/power_supply/BAT*/status | head -1)
@@ -100,9 +109,3 @@ while true; do
     joplin-sync >/dev/null 2> /dev/null &
     sleep 3590s
 done &
-
-# export possible screenlayouts and set default one with `arandr`
-sleep 1 && default_screenlayout >/dev/null 2> /dev/null &
-
-# enable transparent windows (doing this with 'start' doesn't work)
-sleep 2 && picom --experimental-backends >> "$HOME"/.local/share/dwm_autostart.log 2>> "$HOME"/.local/share/dwm_autostart.errors.log &
